---
title: "A simple run through of RDM with BBS data"
author: "Jessica Burnett"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Vignette Title}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)

```

There are a lot of dependencies to load here.

```{r , message=FALSE, warning = FALSE}
## Re-install often as this package is under major development.
devtools::install_github("trashbirdecology/regimedetectionmeasures", force = T)
library(regimeDetectionMeasures)
library(sp)
library(raster)
library(feather)
library(bbsRDM)
```

First we need to create some directories to hold the intermediate data.
```{r}
# a. Create a directory to store and/or load the BBS data as feathers
bbsDir <- here::here("bbs_raw_data")
dir.create(bbsDir)
# if this returns a warning, proceed with caution as directory already exists
# and may contain results.

# b. Create a directory to store and/or load the BBS data as feathers
resultsDir <- here::here("myResults")
dir.create(resultsDir)
# ditto
```

If necessary, download all the state data. This takes 10-15 minutes, so don't do
this more than once if possible!

```{r , eval = FALSE}
# o. Load the regional .txt file from Patuxent
regions <- GetRegions()
# Create a series or one filenames for states, regions
regionFileName <- regions$zipFileName %>% na.omit()
# a.  Download and unzip the BBS data.
for(i in 1:length(regionFileName)){
        bbsData <-  importDataBBS(
            # arguments for getDataBBS()
            file = regionFileName[i],
            dir =  "ftp://ftpext.usgs.gov/pub/er/md/laurel/BBS/DataFiles/States/",
            year = NULL,
            aou = NULL,
            countrynum = NULL,
            states = NULL,
            #  arguments for getRouteInfo():
            routesFile = "routes.zip",
            routesDir =  "ftp://ftpext.usgs.gov/pub/er/md/laurel/BBS/DataFiles/",
            RouteTypeID = 1,
            # one or more of c(1,2,3)
            Stratum = NULL,
            BCR = NULL
        )


# b. Save the file to disk
birdsToFeathers(dataIn  = bbsData,
                newDir  = bbsDir,
                filename = regionFileName[i])

rm(bbsData)

} # end section I. loop

```

Next we build the sampling grid to force route information onto a regular grid.

```{r}
# III: Build sampling grid --------------------------------------------------------
# Define the grid's cell size (lat, long; unit:degrees)
# 1 deg latitude ~= 69 miles
# 1 deg longitude ~= 55 miles
cs <-
    c(0.5, 0.5)  # default is cell size 0.5 deg lat x 0.5 deg long

# Create the grid
routes_gridList <- createSamplingGrid(cs = cs)
routes_grid <- routes_gridList$routes_grid
sp_grd <- routes_gridList$sp_grd

rm(cs)

```

